project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Menna Bishop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv_sep_26.pdf
        text: CV
        target: _blank
  page-footer:
    left: "© 2026 Menna Bishop"

format:
  html:
    theme: lux
    toc: false
    grid:
      body-width: 800px

engine: knitr
